Support TLCP based on Tongsuo
Tongsuo-Project/curl pull request #1
Opened 2022-11-04 11:58 UTC by dongbeiouba

2022-11-05 09:06 UTC, dongbeiouba commented
帮忙review，失败的CI  Linux / hyper 与这个PR无关，原curl/curl就有问题，后续从上游合并解决该问题。

2022-11-14 09:26 UTC, wa5i approved these changes

2022-11-23 10:17 UTC, zhangrui926 commented
curl.h中在SSL的宏定义中增加了ntls的定义，下面2277/2290行是否需要做相应的增加？CURL_SSLVERSION_MAX_NTLSv1_1 = (CURL_SSLVERSION_NTLSv1_1 << 16),

2022-11-29 03:47 UTC, dongbeiouba commented
修复了CI问题，ping @InfoHunter @wa5i

2022-11-29 06:21 UTC, wa5i commented on src/tool_getparam.c
> +  {"Yk", "enc-key",                 ARG_FILENAME},
短名字为啥不用 ec、ek，以及 sc、sk 啊？

2022-11-29 08:29 UTC, InfoHunter requested changes

2022-11-29 08:29 UTC, InfoHunter commented on lib/setopt.c
> +     * String that holds file name of the SSL sign certificate to use
注释有误，应该是SSL enc certificate

2022-11-29 08:29 UTC, InfoHunter commented on lib/setopt.c
> +     * String that holds file name of the SSL sign certificate to use
注释有误，应该是SSL enc key

2022-11-29 08:29 UTC, InfoHunter commented on src/tool_getparam.c
> +  {"Yk", "enc-key",                 ARG_FILENAME},
Ec和Ek与之前的重复了。Sc和Sk上面已经用了。看起来curl的缩写风格是：两个字母，首字母大写，第二个字母小写。如果含义不同且存在差异，则不能仅仅依靠大小写来区分选项，容易混淆。比如用小写的ec和ek表示enc-cert和enc-key的话，容易和Ec和Ek误用，但是类似s和S这种类似开关属性的则没问题

2022-12-02 09:50 UTC, zhangrui926 commented
现在的pr加个宏定义#define HAVE_NTLS就可以了。

2022-12-04 18:50 UTC, InfoHunter approved these changes

2022-12-05 02:24 UTC, merged